version: 1.2
workflows:
 - name: Kraken2_PE_transfer
   subclass: WDL
   primaryDescriptorPath: /workflows/Kraken2_PE_transfer.wdl
 - name: TransferTheiaProk
   subclass: WDL
   primaryDescriptorPath: /workflows/TransferTheiaProk.wdl
 - name: Preprocess_illumina_pe_fastqs
   subclass: WDL
   primaryDescriptorPath: /workflows/preprocess_illumina_pe_fastqs.wdl